### PR TITLE
Create ee4-visual_composer411

### PR DESCRIPTION
**Pull request by chasecmiller**
Bring Visual Composer into the back end editor of Event Espresso.

### CODE REVIEW

**Comment by mnelson4** [comment]
what happened? sounded good...

**Comment by chasecmiller** [comment]
It works well.  Using it now.   I would prefer to write it as a snippet that doesn't dig into the VC code.  I'll work that up next week.

**Comment by mnelson4** [comment]
oh cool; ya requiring editing the VC code was a major downside

**Comment by chasecmiller** [comment]
Check out pull 5 ( https://github.com/eventespresso/ee-code-snippet-library/pull/5/files )

No core editing, just a snippet for whatever file.  Probably should test harder for the global, but it works well.

**Pull request closed without merging**
